### PR TITLE
Add Apache image/service which enables basic auth function

### PR DESCRIPTION
**Pull request by pezhang**
1. Generate an image which enables Apache server with basic auth
2. Start the Apache service

### CODE REVIEW

**Comment by pezhang** [comment]
Tests locally:

$ make  build-apache-basic-auth-image
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  2057  100  2057    0     0   1291      0  0:00:01  0:00:01 --:--:--  1290
Sending build context to Docker daemon  60.08MB
Step 1/4 : FROM registry.redhat.io/rhscl/httpd-24-rhel7
latest: Pulling from rhscl/httpd-24-rhel7
eae19a56e9c6: Pull complete 
be73321c7956: Pull complete 
11fa90307b10: Pull complete 
9e623f734409: Pull complete 
Digest: sha256:31ffa1aa5152b61fb629cd98b0cd72577fa001fc16f73e077ec0750f478984a9
Status: Downloaded newer image for registry.redhat.io/rhscl/httpd-24-rhel7:latest
 ---> 649628158f41
Step 2/4 : ADD apache-basic-auth/chartBasicAuth /var/www/html/chartBasicAuth
 ---> f6c004a7e3bd
Step 3/4 : ADD apache-basic-auth/helm.conf  /etc/httpd/conf.d/helm.conf
 ---> b0b299767a44
Step 4/4 : CMD run-httpd
 ---> Running in d9c4b3092058
Removing intermediate container d9c4b3092058
 ---> 3e665e044a03
Successfully built 3e665e044a03
Successfully tagged apache-basic-auth-image:latest


$ make boot-apache-basic-auth-service
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  2057  100  2057    0     0    538      0  0:00:03  0:00:03 --:--:--   538
Sending build context to Docker daemon  60.08MB
Step 1/4 : FROM registry.redhat.io/rhscl/httpd-24-rhel7
 ---> 649628158f41
Step 2/4 : ADD apache-basic-auth/chartBasicAuth /var/www/html/chartBasicAuth
 ---> Using cache
 ---> f6c004a7e3bd
Step 3/4 : ADD apache-basic-auth/helm.conf  /etc/httpd/conf.d/helm.conf
 ---> Using cache
 ---> b0b299767a44
Step 4/4 : CMD run-httpd
 ---> Using cache
 ---> 3e665e044a03
Successfully built 3e665e044a03
Successfully tagged apache-basic-auth-image:latest
dc9dab5c0b0341dcc5a42599a38c0294fbd0f566f3ffa8ff6529ae6d082467cd

$ docker ps -a
CONTAINER ID        IMAGE                                           COMMAND                  CREATED             STATUS                      PORTS                                                                                                      NAMES
dc9dab5c0b03        apache-basic-auth-image                         "container-entrypoin…"   40 seconds ago      Up 39 seconds               0.0.0.0:8080->8080/tcp, 8443/tcp                                                                           apache-basic-auth-container

**Comment by pezhang** [comment]
This patch is to solve the web server with basic auth, it's related patch will be: https://github.com/open-cluster-management/applifecycle-backend-e2e/pull/14

**Comment by ianzhang366** [comment]
@pezhang everything looks great! thanks for doing this!

I feel we should make the helm repo image generation to the applifecycle-backend-e2e repo, in that way, more operators can benefit from it

**Comment by pezhang** [comment]
Close this patch, as @ianzhang366 suggested, move this to applifecycle-backend-e2e:
https://github.com/open-cluster-management/applifecycle-backend-e2e/pull/19

**Pull request closed without merging**
