### PR TITLE
Download kubectl on macOS

### PR DESCRIPTION
**Pull request by amitkrout**
Download kubectl binary on macOS

### CODE REVIEW

**Comment by mikeshng** [comment]
Hi @amitkrout thank you so much for your contribution. 

We probably don't want to sudo here for security reasons.
For something easy, can we just check if kubectl is available and if its not just exit with an error code.

If you really want to auto download and install. Do something like this might be better for security:

```
which kubectl 
check if $? is 0 then
KUBECTL_EXEC (or whatever name you want) = `which kubectl`
if not 0 then
mkdir -p bin 
curl
mv kubectl to bin
chmod +x bin/kubectl
KUBECTL_EXEC=realpath ./bin/kubectl
```

I mentioned this previously in https://github.com/open-cluster-management/multicloud-operators-subscription-release/pull/106#discussion_r526932688 but Ian and I agreed its more beneficial to check in the bulk of the e2e framework first then come back and fix this problem. Since you are working in this area of the code, could you please try to do something like what I suggested and remove the `sudo` security risk. Thanks.

**Comment by amitkrout** [comment]
@mikeshng Thanks for the feedback.

I have addressed your suggestion. Instead of directly using the binary, i put ```bin/``` into PATH. PTAL

**Comment by amitkrout** [comment]
```
+make lint
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100    90  100    90    0     0    359      0 --:--:-- --:--:-- --:--:--   360
.build-harness-bootstrap:1: *** missing separator.  Stop.
The command "bash ${TRAVIS_BUILD_DIR}/build/run-code-lint.sh" exited with 2.
```

lint check is failing

**Comment by mikeshng** [comment]
@amitkrout the travis build doesn't support fork PRs.

Could you please do this and reopen the PR:
- clone the repo
- git checkout master
- git checkout -b branch_name_you_want
- make your changes and git add and git commit
- git push origin branch_name_you_want
- recreate the PR

sorry for the trouble and thank you for the good work

**Comment by amitkrout** [comment]
@mikeshng Np, i will create separate pr. thanks

**Pull request closed without merging**
