### PR TITLE
fix a bad error message when the type is git

### PR DESCRIPTION
**Pull request by mikeshng**
Signed-off-by: Mike Ng <ming@redhat.com>

### CODE REVIEW

**Review by rokej — COMMENTED** [review]
@mikeshng The HelmRelease CRD does not have Repo.Source.Git.

**Comment by mikeshng** [comment]
@rokej Uh oh, its in the code but its not strictly defined in the CRD.

https://github.com/open-cluster-management/multicloud-operators-subscription-release/blob/main/pkg/apis/apps/v1/helmrelease_types.go#L70-L71
vs
https://github.com/open-cluster-management/multicloud-operators-subscription-release/blob/main/deploy/crds/apps.open-cluster-management.io_helmreleases_crd_v1.yaml#L123-L154

What do you think we should do in this case? Just fix the error message to mention Repo.Source.GitHub for now?

**Comment by mikeshng** [comment]
@rokej fixed as discussed. I will fix the app subscription side after this is merged.

**Review by rokej — APPROVED** [review]
Thanks @mikeshng

**Pull request merged**
